### ISSUE TITLE
##INFO format in VCF file

### ISSUE THREAD

**Issue by dakl** [konradjk/exac_browser#164]
While writing I realised that my issue has been addressed in the latest version of the ExAC VCF. Closing...

**Comment by dakl** [comment]
Reopening; 

The INFO fields

```
##INFO=<ID=DP_HIST,Number=A,Type=String,Description="Histogram for DP; Mids: 2.5|7.5|12.5|17.5|22.5|27.5|32.5|37.5|42.5|47.5|52.5|57.5|62.5|67.5|72.5|77.5|82.5|87.5|92.5|97.5">
##INFO=<ID=GQ_HIST,Number=A,Type=String,Description="Histogram for GQ; Mids: 2.5|7.5|12.5|17.5|22.5|27.5|32.5|37.5|42.5|47.5|52.5|57.5|62.5|67.5|72.5|77.5|82.5|87.5|92.5|97.5">
```

should be of type `R`, i.e. one item per allele (including ref), rather than the current `A` which is one per **alternative** allele. The actual values for each variant seem to contain first the DP histogram for the ref allele, and then each alt. 

From the VCF 4.2 spec:

1.2.2 Information field format

...

• If the field has one value per alternate allele then this value should be ‘A’.
• If the field has one value for each possible allele (including the reference), then this value should be ‘R’.

Thanks a lot for making this resource public.

**Comment by dakl** [comment]
Also, for the `Het_*` fields, there is one too many items in the list when alleles are multiallelic. The INFO field says `Number=A`, but for these variants (including two examples): 

```
1       13404   .       G       A,T
1       13528   .       C       G,T 
```

, the `HET_*` fields are

```
Het_AFR=0,0,0;Het_AMR=0,0,0;Het_EAS=0,0,0;Het_FIN=0,0,0;Het_NFE=0,0,0;Het_OTH=0,0,0;Het_SAS=0,1,0
Het_AMR=1,0,0;Het_EAS=0,0,0;Het_FIN=0,0,0;Het_NFE=0,2,0;Het_OTH=0,0,0;Het_SAS=0,7,0
```

For biallelic variants there is only a single filed, as expected from `Number=A`. 

For site with 3 alt alleles (ex `1	69552	rs55874132	G	T,A,C`), there are six items: 

```
Het_FIN=0,0,0,0,0,0;Het_NFE=0,0,0,0,0,0;Het_OTH=0,0,0,0,0,0;Het_SAS=0,1,0,0,0,0
```

From where I stand, this means one of these two things: 

1. There is a bug in the script generating the `Het_*` tags for multiallelic variants, **or**, 
2. There are interactions going on, so the items listed include the number of individuals with a combination of alt alleles, which means that `Number=A` is incorrect and should be `Number=.` (unbounded/unknown) and described in the header. 

Thanks again, 

Daniel

**Comment by monkollek** [comment]
Hi Daniel,

Thank you very much for the feedback!

Regarding the comment on the Het_* field, it is (2) as it is an ordered list of all possible Het pairs (i.e. "interations going on"). You are right that strictly speaking it should be Number=. and not Number=A and so will be fixed in the next release.

**Comment by dakl** [comment]
:) Makes for easier parsing.

**Comment by konradjk** [comment]
Re: Number=R, you're totally right, I hadn't seen this new convention in VCF 4.2 yet! We can change this and increment our VCF version number in the next version.

**Comment by dakl** [comment]
Great, thanks! Just realized now that R is new to the 4.2 spec, which also explains why it's missing from htsjdk 1.120...  :)

**Comment by konradjk** [comment]
Apologies for the delay, this is now fixed in release 0.3.1: ftp://ftp.broadinstitute.org/pub/ExAC_release/release0.3.1

**Comment by Jalini** [comment]
Hello All,

I'm trying to parse raw VCF version 0.3.1 and the header has following information.
![image](https://cloud.githubusercontent.com/assets/14094633/15584620/6b2d1710-2349-11e6-8dbc-33db5ebe2c69.png)


So basically as an example if I want to parse multiallelic situation into separate fields for following:

Chr 2: pos 229937 Ref :TG ALT : CG, T AC_Het :1,1,0 into separate records how should it be look like?

I'm assuming it should be like following since Number =R in the INFO section:
chr   pos               Ref    ALT   AC_Het
2      229937         TG    CG     1
2      229937          TG    T        1

What if there are more than 2 ALTs?
as an example: CHR :2 POS: 271998   REF: CAAA     ALT: CA, CAA, CAAAA, C,CAAAAA, CAAAAAA  AC_HET:272,12937,8416,2,136,8,16465,156,0,4,1,13695,86,323,18,0,141,2,0,0,0

I would like to know what type of logic I should be using in order to parse these HET_* fields since I'm using a python parser to extract these information from RAW VCF. Also I know that Borad institute has published table format data for ExAC data version 0.3.1 and it shows AC_HET as following for the examples that i have given above.
CHROM	POS	REF	ALT	AC_Het

2	229937	T	C	1
2	229937	TG	T	1


second example:
2	271998	CAA	C	272
2	271998	CA	C	12937
2	271998	C	CA	8416
2	271998	CAAA	C	2
2	271998	C	CAA	136
2	271998	C	CAAA	8

Any advice would be much appreciated.

**Comment by dakl** [comment]
Have a look at the vcf spec section 1.2.2 for details on what number=R
means. In short, it's "one item for each allele INCLUDING the reference
allele".

The Ref comes first and therefore gets AC_HET=1, the first ALT gets the
second 1, and the second ALT has 0.

http://samtools.github.io/hts-specs/VCFv4.2.pdf

(Sent from mobile, please excuse any misspellings)

BR

Daniel
tors 26 maj 2016 kl. 20:08 skrev jalinir@bu.edu <notifications@github.com>:

**Comment by Jalini** [comment]
Thank you Daniel.

Based on boradinstitute table data this is what i have for the same Chr 2 : 229937 .

ftp://ftp.broadinstitute.org/pub/ExAC_release/current/manuscript_data/, file name ExAC.r0.3.1.sites.vep.table.gz

CHROM	POS	REF	ALT	AC_Het
2	229937	T	C	1
2	229937	TG	T	1


Is this correct based on 1.2.2?  

Thank you for your quick response.

Jalini
