### ISSUE TITLE
Incorrect amino acid prediction for variant

### ISSUE THREAD

**Issue by rmhasle** [konradjk/exac_browser#187]
The prediction (p.Arg149Ter) given for variant 19:11230785 A / T is incorrect and should be p.Thr621Thr

**Comment by dgmacarthur** [comment]
Hi - the gene page shows the worst annotation across all transcripts for that specific variant. In this case one of the Gencode transcripts (ENST00000559340) has a different reading frame from the others, and as a result the impact of this variant is a nonsense rather than synonymous substitution. (This transcript is likely to be spurious, but it is nonetheless a valid Gencode transcript.)

To see the functional impact of variants with respect to the canonical transcript you can select the starred transcript from the drop-down menu at the top of the page - in this case http://exac.broadinstitute.org/transcript/ENST00000558518.
