### ISSUE TITLE
Variant not found in ExAC

### ISSUE THREAD

**Issue by simonbrent** [konradjk/exac_browser#215]
Hi. When I go to the following page, I get the message "This variant is not found in ExAC", despite the variant existing in the ExAC.r0.3.sites.vep.vcf.gz file.

http://exac.broadinstitute.org/variant/9-71395127-CGGGCGGGAGCCCGGCGGA-TGGGCGGGAGCCCGGCGGA

**Comment by dgmacarthur** [comment]
Hi Simon,

This is a variant representation issue. In the browser this variant is correctly represented as a SNP, http://exac.broadinstitute.org/variant/9-71395127-C-T. However in the VCF it can't be represented in this fashion because of a large deletion at the same site, http://exac.broadinstitute.org/variant/9-71395127-CGGGCGGGAGCCCGGCGGA-C. As a result of this deletion we are forced to add padding bases to the SNP as well.

We appreciate this is confusing and wish there was a simple solution - there isn't. Our recommendation is to always consider varying allele representation and preferably use tools like vt-normalize to reduce variants to their "minimal representation" (which in this case is the C>T SNP).
