### ISSUE TITLE
One of my colleagues suggested that it may be the releases your were using, hg37 vs hg38.

### ISSUE THREAD

**Issue by pbyers43** [konradjk/exac_browser#253]
We recently identified mutations in C1R in a genetic disorder and in the course of trying to determine if the variants had been identified went to the ExAC data base and found that the numbering system for the canonical sequence is off, probably because it is a partial hybrid of two sequences.

In the canonical sequence, ENST00000542285, the first exon contains only two coding nucleotides (AT) of the initiator methionine and the third nucleotide is then in exon 2.  This is layed out clearly in the Ensembl "exons" tab for the sequence.   Your sequence is a hybrid and starts with the coding sequence of ENST00000536053, which has a longer first exon, and then reverts to the sequence of the canonical sequence, but in so doing misnumbers the amino acids by 1 position so that the Val at position 8 of the canonical sequence is listed at position 7 in the ExAC listing for the canonical sequence, the Pro at position 9 is at 8 in ExAC.

Once I figured this out, I can see that none of the variants we identified are in the ExAC listing, and so was greatly relieved.  But one of our colleagues mislabeled the positions of three of their variants so that they seem to accord to the ExAC sequence alignments but not to the canonical ones.  I cannot find a reference full length sequence that seems to have that alignment, though.

Do you think you can fix the alignments for  ENST00000542285 in the browser.

Many thanks,

Peter Byers

**Comment by dgmacarthur** [comment]
Hi Peter,

Thanks for your note. Unfortunately we are dependent on the annotations in the Ensembl database, and don't have the manpower to change them manually for specific genes.

As your colleagues have noted, ExAC is aligned to hg37, so we are dependent on a somewhat older version of the Ensembl annotations which may be out of date in this case (I haven't confirmed this). If the problem you describe here has been fixed in the latest Ensembl release, then this issue will disappear later this year when we release the next ExAC version (which will have a version that is lifted over onto hg38). If it is not fixed in later Ensembl releases then it would be worth contacting their helpdesk to ensure it is corrected in future releases.


Daniel.

**Comment by pbyers43** [comment]
Daniel,

Thanks.

Peter

Peter H. Byers, MD
Departments of Pathology and Medicine (Medical Genetics)
Box 357470
University of Washington
Seattle, WA 98195-7470
Phone:	206-543-4206
FAX:		206-616-1899
Collagen Diagnostic Laboratory: http://www.pathology.washington.edu/clinical/collagen/

Privileged, confidential or patient identifiable information may be contained in this message. This information is meant only for the use of the intended recipients. If you are not the intended recipient, or if the message has been addressed to you in error, do not read, disclose, reproduce, distribute, disseminate or otherwise use this transmission.  Instead, please notify the sender by reply e-mail, and then destroy all copies of the message and any attachments.
