### ISSUE TITLE
PRSS1 mutation with frequency of 47%

### ISSUE THREAD

**Issue by Andre3w** [konradjk/exac_browser#264]
The PRSS1 disease-causing mutation rs111033566 is reported with an allele frequency of 47% (with no homozygotes reported). How is this possible? It is one of the two most common disease-causing mutations in PRSS1.

**Comment by dgmacarthur** [comment]
Hi Andrew,

The variant is actually filtered in ExAC with the InbreedingCoeff_Filter flag (i.e. it wouldn't show up in standard searches) - this is because it has too many heterozygotes. This filter is characteristic of a mapping error. Sure enough, the region in question is highly similar to the paralogous region in PRSS2, and it turns out that the N29I variant is actually present in PRSS2 and that its occurrence in PRSS1 patients is due to gene conversion with PRSS2 (e.g. http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2752332/).

So everything appears to be in order: this is a mapping error due to reads from PRSS2 being falsely mapped to PRSS1, and it has correspondingly been filtered in ExAC. It only shows up because (presumably) you did a directed search for the variant, and you can see that it's been filtered by the big red label at the top of the page.

**Comment by Andre3w** [comment]
Hello Daniel,

many thanks for the thorough answer!

Andrea

2016-06-27 15:32 GMT+02:00 Daniel MacArthur <notifications@github.com>:
